- name: Set timezone to Europe/Amsterdam
  timezone:
    name: Europe/Amsterdam
  become: yes
  when:
    - "'backupserver' in group_names"

- name: Copy Private SSH Key
  copy:
    src: ../files/id_rsa
    dest: .ssh/id_rsa
    owner: "{{ adminname }}"
    group: "{{ adminname }}"
    mode: '600'
  when:
  - "'backupserver' in group_names"

- name: Make Backupfolder
  file:
    path: /home/{{ adminname }}/backups
    state: directory
    mode: '0775'
  when:
  - "'backupserver' in group_names"
