- name: Installeren NFS server
  apt:
    name: nfs-kernel-server
    update_cache: yes
  become: yes
  when:
    - "'nfsservers' in group_names"

- name: Aanmaken NFS directory
  file:
    path: /var/webshare
    state: directory
    mode: '0755'
    owner: "{{ adminname }}"
    group: "{{ adminname }}"
  become: yes
  when:
    - "'nfsservers' in group_names"

- name: Downloaden wordpress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz
    validate_certs: no
  when:
    - "'nfsservers' in group_names"

- name: Extract wordpress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/ copy=no
  become: yes
  when:
    - "'nfsservers' in group_names"

- name: Server configureren
  lineinfile:
   path: /etc/exports
   line: '/var/wordpress 10.0.0.0/24(rw,no_root_squash,no_subtree_check)'
  become: yes
  when:
    - "'nfsservers' in group_names"

- name: Configuratie afronden doorgeven
  shell: exportfs -r
  become: yes
  when:
    - "'nfsservers' in group_names"

- name: Herstarten NFSkernel service
  service:
    name: nfs-kernel-server
    state: reloaded
  become: yes
  when:
    - "'nfsservers' in group_names"


- name: Instellen cronjob voor backups
  cron:
    name: "Backup maken"
    minute: "0"
    hour: "20"
    job: "tar -czf /tmp/backup-$(date +%Y-%m-%d).tar.gz /var/webshare && scp /tmp/backup-$(date +%Y-%m-%d).tar.gz backup_user@{{ private_ip_backup }} /var/backups/"
  when:
    - "'nfsservers' in group_names"
