- name: Installeren NFS server
  apt:
    name: nfs-kernel-server
    update_cache: yes
  become: yes
  when:
    - ansible_hostname == nfsname

- name: Aanmaken NFS directory
  file:
    path: /var/webshare
    state: directory
    mode: '0755'
    owner: "{{ adminname }}"
    group: "{{ adminname }}"
  become: yes
  when:
    - ansible_hostname == nfsname

- name: Server configureren
  lineinfile:
   path: /etc/exports
   line: '/var/webshare 10.0.0.0/24(rw,no_root_squash,no_subtree_check)'
  become: yes
  when:
    - ansible_hostname == nfsname

- name: Configuratie afronden & herstarten
  shell: exportfs -r
  become: yes
  when:
    - ansible_hostname == nfsname

- name: Herstarten NFSkernel service
  service:
    name: nfs-kernel-server
    state: reloaded
  become: yes

  when:
    - ansible_hostname == nfsname

- name: Instellen cronjob voor backups
  cron:
    name: "Backup maken"
    minute: "0"
    hour: "20"
    job: "tar -czf /tmp/backup-$(date +%Y-%m-%d).tar.gz /var/webshare && scp /tmp/backup-$(date +%Y-%m-%d).tar.gz backup_user@{{ private_ip_backup }} /var/backups/"
