- name: Install NFS service
  apt:
    name: nfs-kernel-server
    update_cache: yes
  become: yes
  when:
    - "'nfsservers' in group_names"

- name: Create NFS directory
  file:
    path: /var/webshare
    state: directory
    mode: '0755'
    owner: "{{ adminname }}"
    group: "{{ adminname }}"
  become: yes
  when:
    - "'nfsservers' in group_names"

- name: Download WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz
    validate_certs: no
  when:
    - "'nfsservers' in group_names"

- name: Extract WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /tmp
    remote_src: yes
  become: yes
  when:
    - "'nfsservers' in group_names"

- name: Copy WordPress content to NFS Share
  shell: cp -R /tmp/wordpress/* /var/webshare
  become: yes
  when:
    - "'nfsservers' in group_names"

- name: Copy sample config file
  command: mv /var/webshare/wp-config-sample.php /var/webshare/wp-config.php
  become: yes
  when:
    - "'nfsservers' in group_names"

- name: Update WordPress config file
  lineinfile:
    dest: /var/webshare/wp-config.php
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - {'regexp': "define\\('DB_NAME', '(.)+'\\);", 'line': "define('DB_NAME', '{{ mysql_database_name }}');"}
    - {'regexp': "define\\('DB_USER', '(.)+'\\);", 'line': "define('DB_USER', '{{ mysql_user_name }}');"}
    - {'regexp': "define\\('DB_PASSWORD', '(.)+'\\);", 'line': "define('DB_PASSWORD', '{{ mysql_user_password }}');"}
  become: yes
  when:
    - "'nfsservers' in group_names"

- name: Designate webshare
  lineinfile:
   path: /etc/exports
   line: '/var/webshare 10.0.0.0/24(rw,no_root_squash,no_subtree_check)'
  become: yes
  when:
    - "'nfsservers' in group_names"

- name: Update etab
  shell: exportfs -r
  become: yes
  when:
    - "'nfsservers' in group_names"

- name: Reload NFS service
  service:
    name: nfs-kernel-server
    state: reloaded
  become: yes
  when:
    - "'nfsservers' in group_names"


- name: Set cron job for backups
  cron:
    name: "Backup maken"
    minute: "0"
    hour: "20"
    job: "tar -czf /tmp/backup-$(date +%Y-%m-%d).tar.gz /var/webshare && scp /tmp/backup-$(date +%Y-%m-%d).tar.gz backup_user@{{ private_ip_backup }} /var/backups/"
  when:
    - "'nfsservers' in group_names"
