---
- name: Installeren van een SQL service
  apt:
    pkg:
    - mysql-server
    - python-mysqldb
    update_cache: yes
  become: yes
  when:
    - "'sqlservers' in group_names"

- name: Modify the mysql config
  shell: sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mysql/mysql.conf.d/mysqld.cnf
  become: yes
  when:
    - "'sqlservers' in group_names"

- name: Herstarten mysqld service
  service:
    name: mysql
    state: restarted
  become: yes
  when:
    - "'sqlservers' in group_names"

- name: Update MySQL root password for all root accounts
  mysql_user:
    name=root
    host={{ item }}
    password={{ mysql_root_password }}
    state=present
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
  become: yes
  when:
    - "'sqlservers' in group_names"

- name: Copy the root credentials as .my.cnf file
  template: src=templates/root.cnf.j2 dest=~/.my.cnf mode=0600
