- name: Installeren van een SQL service
  apt:
    pkg:
    - mysql-server
    - python-mysqldb
    update_cache: yes
  become: yes
  when:
    - "'sqlservers' in group_names"

- name: Modify the mysql config
  shell: sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mysql/mysql.conf.d/mysqld.cnf
  become: yes
  when:
    - "'sqlservers' in group_names"

- name: Herstarten mysqld service
  service:
    name: mysql
    state: restarted
  become: yes
  when:
    - "'sqlservers' in group_names"

- name: Update MySQL root password
  mysql_user:
    login_user: root
    login_host: localhost
    login_password: ""
    name: root
    password: "{{ mysql_root_password }}"
    state: present
  become: yes
  when:
    - "'sqlservers' in group_names"

- name: Add a WP database
  mysql_db:
    login_host: localhost
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: "{{ mysql_database_name }}"
    state: present
  become: yes
  when:
    - "'sqlservers' in group_names"

- name: Add a WP user for database
  mysql_user:
    login_host: localhost
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: "{{ mysql_user_name }}"
    password: "{{ mysql_user_password }}"
    priv: "*.*:ALL,GRANT"
    host: "%"
    state: present
  become: yes
  when:
    - "'sqlservers' in group_names"
