- name: Install packages
  apt:
    pkg:
    - apache2
    - nfs-common
  become: yes
  when:
    - ansible_hostname == "web01" or ansible_hostname == "web02"

- name: Mount NFS folder at boot
  raw: X
  when:
    - ansible_hostname == "web01" or ansible_hostname == "web02"
