- name: Install packages
  apt:
    pkg:
    - apache2
    - nfs-common
  when:
#    - ansible_hostname == web01 or ansible_hostname == web02
  become: yes
#- name: Mount NFS folder at boot
#  raw: X
#  when:
#    - ansible_hostname == "web01" or ansible_hostname == "web02"
