- name: Set timezone to Europe/Amsterdam
  timezone:
    name: Europe/Amsterdam
  become: yes
  when:
    - "'webservers' in group_names"
    
- name: Install packages
  apt:
    pkg:
    - apache2
    - nfs-common
    - php
    - libapache2-mod-php
    - php-mysql
    - php-curl
    - php-gd
    - php-xml
    - php-mbstring
    - php-xmlrpc
    - php-zip
    - php-soap
    - php-intl
    update_cache: yes
  become: yes
  when:
    - "'webservers' in group_names"

- name: NFS Share mounten
  lineinfile:
    path: /etc/fstab
    line: '{{ private_ip_nfs }}:/var/webshare    /var/www/html   nfs auto,nofail,noatime,nolock,intr,tcp,actimeo=1800 0 0'
  become: yes
  when:
    - "'webservers' in group_names"

- name: Reboot servers to mount the share
  reboot:
  become: yes
  when:
    - "'webservers' in group_names"

- name: Set Apache owner permissions
  shell: chown -R root:www-data /var/www/html
  become: yes
  when: "'webservers' in group_names"

- name: Set Apache folder permissions
  shell: find /var/www/html -type d -exec chmod 775 {} \;
  become: yes
  when: "'webservers' in group_names"

- name: Set Apache file permissions
  shell: find /var/www/html -type f -exec chmod 644 {} \;
  become: yes
  when: "'webservers' in group_names"
