---
- hosts: 192.168.1.5
  tasks:
  - name: Check if NFS is running. # Moet nog een SSH check worden toegevoegd
    service:
      name: "{{ item }}"
      state: started
      enabled: yes
    with_items:
      - nfs-kernel-server
      - sshd
    become: yes

  - name: Get service facts
    service_facts:
    register: service_facts
    local_action:
      copy: content="{{ service_facts.ansible_facts.services['nfs-kernel-server'] | to_nice_yaml }}" dest=/home/ansibleuser/nfsserver
    #become: yes
    #blockinfile:
    #  path: /var/www/html/nfsserver.txt
    #  block: "{{ service_facts.ansible_facts.services['sshd'] | to_nice_yaml }}"
  #- local_action: copy content="{{ service_facts.ansible_facts.services['sshd'] | to_nice_yaml }}" dest=/var/www/html/nfsserver.txt #/var/www/html/nfsserver.txt
