---
- hosts: localhost
  connection: local
  gather_facts: true
  roles:
    - deploy
  tasks:
    - name: Set azure_state Deployed
      lineinfile:
        path: group_vars/all
        regexp: '^azure_state:'
        line: 'azure_state: deployed'
    - name: debug
      debug:
        msg: "{{ azure_state }}"

- hosts: confmanagementnode
  gather_facts: true
  roles:
    - { role: mmnode, when: azure_state == "deployed" }

- hosts: allservers
  gather_facts: true
  roles:
    - configure
