---
### Azure Deployment Role ###
- hosts: localhost
  connection: local
  gather_facts: "{{ choice }}"
  vars_prompt:
    - name: choice
      prompt: "Wil je Azure inrichten? (yes/no)"
      private: no

  pre_tasks:
    - name: Include Vars
      include_vars: "{{ item }}"
      with_items:
        - 'vars/secret.yml'
        - 'vars/vars.yml'
      when: choice == "yes"
  roles:
    - { role: deploy, when: choice  == "yes" }

  tasks:
    - name: Set azure_state Deployed
      lineinfile:
        path: group_vars/all
        regexp: '^azure_state:'
        line: 'azure_state: deployed'
      when: choice == "yes"

    - name: Add public ip of the managementnode to the group
      add_host:
        name: "{{ ip_address.state.ip_address }}"
        groups: confmanagementnode
      when: choice == "yes"
    - name: Get ips
      shell: az vmss nic list --resource-group A2S2_GROEP_03 --vmss-name Webscaleset --query "[].ipConfigurations[].privateIpAddress" -o tsv
      register: addresses

    - debug:
        msg: "{{ (addresses.stdout | from_yaml) }}"

    - debug:
        msg: "{{ addresses.stdout }}"

    - local_action: copy content="{{  addresses.stdout }}" dest="ip.txt"

    - name: Add public ip of the managementnode to the group
      add_host:
        name: "{{ addresses.stdout }}"
        groups: servers
      when: choice == "yes"


### Managementnode Configuration role
- hosts: confmanagementnode
  gather_facts: "{{ choice }}"
  vars:
    ansible_user: ansibleuser
    ansible_connection: ssh

  vars_prompt:
    - name: choice
      prompt: "Wil je de management node inrichten? (yes/no)"
      private: no

  pre_tasks:
    - name: Include Vars
      include_vars: "{{ item }}"
      with_items:
        - 'vars/secret.yml'
        - 'vars/vars.yml'
      when: choice == "yes"

  roles:
    - { role: mmnode, when: azure_state == "deployed" and choice == "yes"}

### Configuratie Role ###
- hosts: servers
  gather_facts: "{{ choice }}"
  vars:
    ansible_user: ansibleuser
    ansible_connection: ssh
  vars_prompt:
    - name: choice
      prompt: "Wil je de complete infrastructuur remote laten inrichten? (yes/no)"
      private: no

  ignore_errors: yes
  pre_tasks:
    - name: Include Vars
      include_vars: "{{ item }}"
      with_items:
        - 'vars/secret.yml'
        - 'vars/vars.yml'
      when: choice == "yes"


  roles:
    - { role: configure, when: choice == "yes"}

### Undeployment Role ###
- hosts: localhost
  connection: local
  gather_facts: "{{ choice }}"
  ignore_errors: yes
  vars_prompt:
    - name: choice
      prompt: "Wil je de undeployment starten? (yes/no)"
      private: no

  pre_tasks:
    - name: Include Vars
      include_vars: "{{ item }}"
      with_items:
        - 'vars/secret.yml'
        - 'vars/vars.yml'
      when: choice == "yes"

  roles:
    - { role: undeploy, when: choice == "yes" }
