---
### Azure Deployment Role ###
- hosts: localhost
  connection: local
  gather_facts: "{{ choice }}"
  vars_prompt:
    - name: env
      prompt: "Do you want to make changes in the staging or production environment? (production/staging)"
      private: no

    - name: choice
      prompt: "Do you want to deploy the compute components in Microsoft Azure for 'De Wolk'? (yes/no)"
      private: no


  pre_tasks:
    - name: Include Production Environment variables
      include_vars: "{{ item }}"
      with_items:
        - '{{ env }}/vars/secret.yml'
        - '{{ env }}/vars/vars.yml'
      when: choice == "yes"
    - set_fact:
        env_short: PROD
      when: env == "production"
    - set_fact:
        env_short: STAG
      when: env == "staging"
    - debug:
        var: env_short
  roles:
    - { role: deploy, when: choice  == "yes" }

  tasks:
    - name: Set azure_state deployed
      lineinfile:
        path: group_vars/all
        regexp: '^azure_state:'
        line: 'azure_state: deployed'
      when: choice == "yes"

    - name: Add public IP of the management node to the group
      add_host:
        name: "{{ ip_address.state.ip_address }}"
        groups: confmanagementnode
      when: choice == "yes"


### Managementnode Configuration role
- hosts: confmanagementnode
  gather_facts: "{{ choice }}"
  vars:
    ansible_user: ansibleuser
    ansible_connection: ssh

  vars_prompt:
    - name: env
      prompt: "Do you want to make changes in the staging or production environment? (production/staging)"
      private: no

    - name: choice
      prompt: "Do you want to configure a Management node? (yes/no)"
      private: no

  pre_tasks:
    - name: Include vars
      include_vars: "{{ item }}"
      with_items:
        - '{{ env }}/vars/secret.yml'
        - '{{ env }}/vars/vars.yml'
      when: choice == "yes"

  roles:
    - { role: mmnode, when: choice == "yes"}

### Configuratie Role ###
- hosts: servers
  gather_facts: "{{ choice }}"
  vars:
    ansible_user: ansibleuser
    ansible_connection: ssh
  vars_prompt:
    - name: env
      prompt: "Do you want to make changes in the staging or production environment? (production/staging)"
      private: no

    - name: choice
      prompt: "Do you want to initialize the servers in Azure for 'De Wolk'? (yes/no)"
      private: no

  ignore_errors: yes
  pre_tasks:
    - name: Include vars
      include_vars: "{{ item }}"
      with_items:
        - '{{ env }}/vars/secret.yml'
        - '{{ env }}/vars/vars.yml'
      when: choice == "yes"

  roles:
    - { role: configure, when: choice == "yes"}

### Undeployment Role ###
- hosts: localhost
  connection: local
  gather_facts: "{{ choice }}"
  ignore_errors: yes
  vars_prompt:
    - name: env
      prompt: "Do you want to make changes in the staging or production environment? (production/staging)"
      private: no

    - name: choice
      prompt: "Do you want to start the undeployment of the cloud solution for 'De Wolk'? (yes/no)"
      private: no

  pre_tasks:
    - name: Include vars
      include_vars: "{{ item }}"
      with_items:
        - '{{ env }}/vars/secret.yml'
        - '{{ env }}/vars/vars.yml'
      when: choice == "yes"

  roles:
    - { role: undeploy, when: choice == "yes" }
