---
- hosts: localhost
  connection: local
  gather_facts: true

  pre_tasks:
    - name: Include Vars
      include_vars: "{{ item }}"
      with_items:
        - 'vars/secret.yml'
        - 'vars/vars.yml'

  roles:
    - undeploy
