- name: Copy Private SSH Key
  copy:
    src: ../files/id_rsa
    dest: /home/rens/.ssh/id_rsa
    owner: "rens"
    group: "rens"
    mode: '600'


- name: Adding the Ansible repository
  apt_repository:
    repo: ppa:ansible/ansible
  become: yes

- name: Upgrade all packages to latest version
  apt:
    name: "*"
    state: latest
  become: yes

- name: Install Ansible and Tools
  apt:
    pkg:
    - software-properties-common
    - ansible
    - git
    update_cache: yes
  become: yes

- name: Check of GIT repo er al is
  stat:
    path: /home/rens/casus
  register: stat_result

- name: Get GIT repo from Gitlab
  raw: git clone https://gitlab.com/groep-3-devops/casus.git
  become: false
  when: stat_result.stat.exists == False

- name: Change GIT folder ownership
  raw: chown -R rens:rens /home/rens/casus
  when: stat_result.stat.exists == False
