- name: Copy Private SSH Key
  copy:
    src: ../files/id_rsa
    dest: .ssh/id_rsa
    owner: "{{ adminname }}"
    group: "{{ adminname }}"
    mode: '600'

- name: Set timezone to Europe/Amsterdam
  timezone:
    name: Europe/Amsterdam
  become: yes

- name: Adding the Ansible repository
  apt_repository:
    repo: ppa:ansible/ansible
  become: yes

- name: Upgrade all packages to latest version
  apt:
    name: "*"
    state: latest
  become: yes

- name: Install Ansible and Tools
  apt:
    pkg:
    - software-properties-common
    - ansible
    - git
    - apache2
    - php
    update_cache: yes
  become: yes

- name: Check of GIT repo er al is
  stat:
    path: casus/
  register: stat_result

- name: Get GIT repo from Gitlab
  raw: git clone https://gitlab.com/groep-3-devops/casus.git
  become: false
  when: stat_result.stat.exists == False

- name: Change GIT folder ownership
  raw: chown -R "{{ adminname }}":"{{ adminname }}" /home/"{{ adminname }}"/casus
  when: stat_result.stat.exists == False

- name: Change ansible configuration file
  lineinfile:
    path: /etc/ansible/ansible.cfg
    regexp: '^#host_key_checking = False'
    line: host_key_checking = False
  become: yes

- name: Add facts playbook to cron
  cron:
    name: "Run facts playbook"
    minute: "*/2"
    hour: "*"
    job: "ansible-playbook /home/ansibleuser/casus/azure/facts_gathering.yml -i /home/ansibleuser/casus/azure/hostsprod"
  when: env == "production"

- name: Add facts playbook to cron
  cron:
    name: "Run facts playbook"
    minute: "*/2"
    hour: "*"
    job: "ansible-playbook /home/ansibleuser/casus/azure/facts_gathering.yml -i /home/ansibleuser/casus/azure/hostsstag"
  when: env == "staging"

- name: Remove old index file
  file:
    path: /var/www/html/index.html
    state: absent
  become:

- name: Copy new index file
  copy:
    src: ../files/index.php
    dest: /var/www/html/index.php
  become: yes
