---
- hosts: localhost
  connection: local
  vars_prompt:
    - name: resource_group
      prompt: "Wat is de naam van de resource groep?"
      private: no
      
    - name: aanmaken_vnet
      prompt: "Wil je een vnet aanmaken? ja/nee"
      private: no
    
    - name: naam_vnet
      prompt: "Wat is de naam van het vnet?"
      private: no
      
  tasks:
    - name: Create VNET
      azure_rm_virtualnetwork:
        resource_group: "{{ resource_group }}"
        name: "{{ naam_vnet }}"
        address_prefixes_cidr:
            - "10.0.0.0/16"
    - name: Add Subnet
      azure_rm_subnet:
        resource_group: "{{ resource_group }}"
        name: Front-End
        address_prefix: "10.0.0.0/24"
        virtual_network: vNet01
    - name: Add backend subnet
      azure_rm_subnet:
        resource_group: "{{ resource_group }}"
        name: Back-end
        address_prefix: "10.0.1.0/24"
        virtual_network: "{{ naam_vnet }}"
      when: aanmaken_vnet == "ja"
