newvnetname: Vnet01
vnetprefix: 10.0.0.0/16
frontendsubnetname: Front-End
backendsubnetname: Back-End
managementsubnetname: Management
frontsubnetpfx: 10.0.0.0/24
backsubnetpfx: 10.0.1.0/24
managementsubnetpfx: 10.0.2.0/24
