---
- hosts: localhost
  connection: local
  tasks:
    - name: Create VNET
      azure_rm_virtualnetwork:
        resource_group: A2S2_GROEP_03
        name: MyVnet
        address_prefixes_cidr:
            - "10.0.0.0/16"
        state: absent
