---
- hosts: localhost
  connection: local
  tasks:
    - name: create load balancer
      azure_rm_loadbalancer:
        resource_group: A2S2_GROEP_03
        name: rensloadbalancer
        state: absent
        sku: Basic
        frontend_ip_configurations:
          - name: frontendipconf0
            public_ip_address: loadbalancerip1
        backend_address_pools:
          - name: backendaddrpool0
        probes:
          - name: prob0
            port: 80
        inbound_nat_pools:
          - name: inboundnatpool0
            frontend_ip_configuration_name: frontendipconf0
            protocol: Tcp
            frontend_port_range_start: 90
            frontend_port_range_end: 100
            backend_port: 22
        load_balancing_rules:
          - name: lbrbalancingrule0
            frontend_ip_configuration: frontendipconf0
            backend_address_pool: backendaddrpool0
            frontend_port: 80
            backend_port: 80
            probe: prob0
