---
- hosts: localhost
  connection: local
  tasks:
    - name: verwijderen disk
      azure_rm_manageddisk:
        name: variables.vmnaam
        resource_group: A2S2_GROEP_03
        state: absent
