---
- hosts: localhost
  connection: local
  tasks:
    - name: Create Virtual Network Interface Card
      azure_rm_networkinterface:
        resource_group: A2S2_GROEP_03
        name: vm02nic
        virtual_network: MyVnet
        subnet: Front-End
        state: absent
        ip_configurations:
              - name: ipconfig1
                public_ip_address_name: publicip002
                primary: True
                load_balancer_backend_address_pools:
                  #- "{{ rensloadbalancer.state.backend_address_pools[0].id }}"
                  - name: backendaddrpool0
                    load_balancer: rensloadbalancer
