- hosts: localhost
  vars:
    resource_group: A2S2_GROEP_03
    vmss_name: myScaleSet
    vmss_lb_name: myScaleSetLb
    admin_username: rens
    admin_password: Welkom123!
  tasks:
    - name: Create public IP address
      azure_rm_publicipaddress:
        resource_group: "{{ resource_group }}"
        allocation_method: Static
        name: "{{ vmss_name }}"
        state: absent
