- name: Include network vars
  include_vars:
    file: availabilityset_vars.yml
    
- name: Aanmaken {{ availabset }}
  azure_rm_availabilityset:
    name: "{{ availabset }}"
    resource_group: "{{ resourcegroup }}"
    state: "{{ status }}"
    sku: Aligned
