- name: Aanmaken Backupserver NSG
  azure_rm_securitygroup:
    resource_group: "{{ resourcegroup }}"
    name: "{{ backupname }}"
    rules:
      - name: SSH
        protocol: Tcp
        destination_port_range: 22
        access: Allow
        priority: 1001
        direction: Inbound
    state: "{{ status }}"
  tags:
    - backupnsg
    - backup

- name: Aanmaken Backupserver NIC
  azure_rm_networkinterface:
    resource_group: "{{ resourcegroup }}"
    name: "{{ backupname }}"
    virtual_network: "{{ vnetname }}"
    subnet: Back-End
    security_group: "{{ backupname }}"
    private_ip_address: "{{ private_ip_backup }}"
    private_ip_allocation_method: Static
    state: "{{ status }}"
  tags:
    - backupnic
    - backup

- name: Aanmaken Backup-VM
  azure_rm_virtualmachine:
    resource_group: A2S2_GROEP_03
    name: "{{ backupname }}"
    vm_size: Standard_B2s
    admin_username: "{{ adminname }}"
    ssh_password_enabled: false
    ssh_public_keys:
      - path: /home/{{ adminname }}/.ssh/authorized_keys
        key_data: "{{ sshkey }}"
    network_interfaces: "{{ backupname }}"
    managed_disk_type: Standard_LRS
    image:
      offer: UbuntuServer
      publisher: Canonical
      sku: 16.04-LTS
      version: latest
    state: "{{ status }}"

  tags:
  - backupvm
  - backup
