- name: Create public IP address
  azure_rm_publicipaddress:
    resource_group: "{{ resourcegroup }}"
    allocation_method: Static
    name: "{{ managementnaam }}"
    state: "{{ status }}"
  register: ip_address
  tags:
  - management
  - managementip

- name: Create Network Security Group that allows SSH
  azure_rm_securitygroup:
    resource_group: "{{ resourcegroup }}"
    name: "{{ managementnaam }}"
    rules:
      - name: SSH
        protocol: Tcp
        destination_port_range: 22
        access: Allow
        priority: 1001
        direction: Inbound
    state: "{{ status }}"
  tags:
    - managementnsg
    - management

- name: Create virtual network interface card
  azure_rm_networkinterface:
    resource_group: "{{ resourcegroup }}"
    name: "{{ managementnaam }}"
    virtual_network: "{{ vnetname }}"
    subnet: Management
    security_group: Management-NSG
    public_ip_name: "{{ managementnaam }}"
    private_ip_allocation_method: Static
    private_ip_address: "{{ private_ip_management }}"
    state: "{{ status }}"
  tags:
    - managementnic
    - management

- name: Aanmaken VM managementnode
  azure_rm_virtualmachine:
    resource_group: A2S2_GROEP_03
    name: "{{ managementnaam }}"
    vm_size: Standard_B2s
    admin_username: "{{ adminname }}"
    ssh_password_enabled: false
    ssh_public_keys:
      - path: /home/{{ adminname }}/.ssh/authorized_keys
        key_data: "{{ sshkey }}"
    network_interfaces: "{{ managementnaam }}"
    managed_disk_type: Standard_LRS
    image:
      offer: UbuntuServer
      publisher: Canonical
      sku: 16.04-LTS
      version: latest
    state: "{{ status }}"
    started: "{{ gestart }}"

  tags:
  - managementvm
  - management
