- name: Aanmaken loadbalancer IP
  azure_rm_publicipaddress:
    resource_group: "{{ resourcegroup }}"
    name: "{{ env_short }}"_"{{ loadbalancername }}"
    allocation_method: static
    state: "{{ status }}"
  tags:
  - loadbalancerip
  - loadbalancer

- name: Aanmaken Loadbalancer
  azure_rm_loadbalancer:
    resource_group: "{{ resourcegroup }}"
    name: "{{ env_short }}"_"{{ loadbalancername }}"
    sku: Basic
    state: "{{ status }}"
    frontend_ip_configurations:
      - name: frontendipconf0
        public_ip_address: "{{ env_short }}"_"{{ loadbalancername }}"
    backend_address_pools:
      - name: backendaddrpool0
    probes:
      - name: prob0
        port: 80
        interval: 5
        fail_count: 3
    load_balancing_rules:
      - name: lbrbalancingrule0
        frontend_ip_configuration: frontendipconf0
        backend_address_pool: backendaddrpool0
        frontend_port: 80
        backend_port: 80
        probe: prob0
  tags:
  - loadbalancer
