- name: Include Loadbalancer Vars
  include_vars:
    file: loadbalancer_vars.yml
  tags:
  - loadbalancerip
  - loadbalancer

- name: Aanmaken loadbalancer IP
  azure_rm_publicipaddress:
    resource_group: "{{ resourcegroup }}"
    name: "{{ loadbalancerip }}"
    allocation_method: static
    state: "{{ status }}"
  tags:
  - loadbalancerip
- name: Aanmaken Loadbalancer
  azure_rm_loadbalancer:
    resource_group: "{{ resourcegroup }}"
    name: "{{ loadbalancername }}"
    sku: Basic
    state: "{{ status }}"
    public_ip: "{{ loadbalancerip }}"
    probe_protocol: Tcp
    probe_port: 80
    probe_interval: 10
    probe_fail_count: 3
    protocol: Tcp
    load_distribution: Default
    frontend_port: 80
    backend_port: 80
    idle_timeout: 4
    natpool_frontend_port_start: 50000
    natpool_frontend_port_end: 50040
    natpool_backend_port: 22
    natpool_protocol: Tcp
  tags:
  - loadbalancer
