- name: Include network vars
  include_vars:
    file: network_vars.yml

- name: Aanmaken Vnet
  azure_rm_virtualnetwork:
    resource_group: "{{ resourcegroup }}"
    name: "{{ vnetname }}"
    address_prefixes_cidr:
      - "{{ vnetprefix }}"
    state: "{{ status }}"

- name: Toevoegen Front-End NSG
  azure_rm_securitygroup:
    resource_group: "{{ resourcegroup }}"
    name: "{{ nsgfrontendname }}"
    rules:
      - name: HTTP
        protocol: Tcp
        destination_port_range: "{{ destporthttpfront }}"
        access: Allow
        priority: "{{ priorityhttpfront }}"
        direction: Inbound
    state: "{{ status }}"


- name: Toevoegen Back-end NSG
  azure_rm_securitygroup:
    resource_group: "{{ resourcegroup }}"
    name: "{{ nsgbackendname }}"
    rules:
      - name: SSH
        protocol: Tcp
        destination_port_range: "{{ destportsshback }}"
        access: Allow
        priority: "{{ prioritysshback }}"
        direction: Inbound
    state: "{{ status }}"

- name: Toevoegen Management NSG
  azure_rm_securitygroup:
    resource_group: "{{ resourcegroup }}"
    name: "{{ nsgmanagementname }}"
    rules:
      - name: SSH
        protocol: Tcp
        destination_port_range: "{{ destportsshman }}"
        access: Allow
        priority: "{{ prioritysshman }}"
        direction: Inbound
    state: "{{ status }}"

- name: Toevoegen Frond-end Subnet
  azure_rm_subnet:
    resource_group: "{{ resourcegroup }}"
    name: "{{ frontendsubnetname }}"
    address_prefix: "{{ frontsubnetpfx }}"
    virtual_network: "{{ vnetname }}"
    state: "{{ status }}"
    security_group: "{{ nsgfrontendname }}"

- name: Toevoegen Backend Subnet
  azure_rm_subnet:
    resource_group: "{{ resourcegroup }}"
    name: "{{ backendsubnetname }}"
    address_prefix: "{{ backsubnetpfx }}"
    virtual_network: "{{ vnetname }}"
    state: "{{ status }}"
    security_group: "{{ nsgbackendname }}"

- name: Toevoegen Management Subnet
  azure_rm_subnet:
    resource_group: "{{ resourcegroup }}"
    name: "{{ managementsubnetname }}"
    address_prefix: "{{ managementsubnetpfx }}"
    virtual_network: "{{ vnetname }}"
    state: "{{ status }}"
    security_group: "{{ nsgmanagementname }}"
