- name: Aanmaken Vnet
  azure_rm_virtualnetwork:
    resource_group: "{{ resourcegroup }}"
    name: "{{ env_short }}-{{ vnetname }}"
    address_prefixes_cidr:
      - "{{ vnetprefix }}"
    state: "{{ status }}"
  tags:
  - vnet
  - network

- name: Toevoegen NSG
  azure_rm_securitygroup:
    resource_group: "{{ resourcegroup }}"
    name: "{{ env_short }}-{{ item.nsgname }}"
    rules:
      - name: "{{ item.rulename }}"
        protocol: "{{ item.protocol }}"
        destination_port_range: "{{ item.destportrange }}"
        access: "{{ item.access }}"
        priority: "{{ item.priority }}"
        direction: "{{ item.direction}}"
    state: "{{ item.status }}"
  with_items: "{{ network.nsgs }}"
  tags:
  - subnetnsg
  - network

- name: Toevoegen Subnets
  azure_rm_subnet:
    resource_group: "{{ resourcegroup }}"
    name: "{{ env_short }}-{{ item.subnetname }}"
    address_prefix: "{{ item.prefix }}"
    virtual_network: "{{ env_short }}-{{ vnetname }}"
    state: "{{ item.status }}"
    security_group: "{{ env_short }}-{{ item.securitygroup }}"
  with_items: "{{ network.subnets }}"
  tags:
  - subnet
  - network
