- name: Aanmaken NFSServer NSG
  azure_rm_securitygroup:
    resource_group: "{{ resourcegroup }}"
    name: "{{ nfsname }}"
    rules:
      - name: SSH
        protocol: Tcp
        destination_port_range: 22
        access: Allow
        priority: 1001
        direction: Inbound
    state: "{{ status }}"
  tags:
    - nfsnsg
    - nfs

- name: Aanmaken NFSserver NIC
  azure_rm_networkinterface:
    resource_group: "{{ resourcegroup }}"
    name: "{{ nfsname }}"
    virtual_network: "{{ vnetname }}"
    subnet: Back-End
    security_group: "{{ nfsname }}"
    private_ip_address: "{{ private_ip_nfs }}"
    private_ip_allocation_method: Static
    state: "{{ status }}"
  tags:
    - nfsnic
    - nfs

- name: Aanmaken NFSServer VM
  azure_rm_virtualmachine:
    resource_group: A2S2_GROEP_03
    name: "{{ nfsname }}"
    vm_size: Standard_B2s
    admin_username: "{{ adminname }}"
    ssh_password_enabled: false
    ssh_public_keys:
      - path: /home/{{ adminname }}/.ssh/authorized_keys
        key_data: "{{ sshkey }}"
    network_interfaces: "{{ nfsname }}"
    managed_disk_type: Standard_LRS
    image:
      offer: UbuntuServer
      publisher: Canonical
      sku: 16.04-LTS
      version: latest
    state: "{{ status }}"
    started: "{{ gestart }}"

  tags:
  - nfsvm
  - nfs
