- name: Create public IP address
  azure_rm_publicipaddress:
    resource_group: "{{ resourcegroup }}"
    allocation_method: Static
    name: "{{ nfsname }}"
    state: "{{ status }}"
  register: ip_address
  tags:
  - nfs
  - nfsip

- name: Create Network Security Group that allows SSH
  azure_rm_securitygroup:
    resource_group: "{{ resourcegroup }}"
    name: "{{ nfsname }}"
    rules:
      - name: nfsname
        protocol: Tcp
        destination_port_range: 22
        access: Allow
        priority: 1001
        direction: Inbound
    state: "{{ status }}"
  tags:
    - nfsnsg
    - nfs

- name: Create virtual network interface card
  azure_rm_networkinterface:
    resource_group: "{{ resourcegroup }}"
    name: "{{ nfsname }}"
    virtual_network: "{{ vnetname }}"
    subnet: Back-End
    security_group: Back-End-NSG
    public_ip_name: "{{ nfsname }}"
    private_ip_allocation_method: Static
    private_ip_address: "{{ private_ip_nfs }}"
    state: "{{ status }}"
  tags:
    - nfsnic
    - nfs

- name: Aanmaken VM nfs-server
  azure_rm_virtualmachine:
    resource_group: A2S2_GROEP_03
    name: "{{ nfsname }}"
    vm_size: Standard_B2s
    admin_username: "{{ adminname }}"
    nfsname_password_enabled: false
    nfsname_public_keys:
      - path: /home/{{ adminname }}/.nfsname/authorized_keys
        key_data: "{{ nfsnamekey }}"
    network_interfaces: "{{ nfsname }}"
    managed_disk_type: Standard_LRS
    image:
      offer: UbuntuServer
      publisher: Canonical
      sku: 16.04-LTS
      version: latest
    state: "{{ status }}"
    started: "{{ gestart }}"

  tags:
  - nfsvm
  - nfs

