- name: Aanmaken SQL Server NSG
  azure_rm_securitygroup:
    resource_group: "{{ resourcegroup }}"
    name: "{{ env_short }}-{{ sqlname }}"
    rules:
      - name: SSH
        protocol: Tcp
        destination_port_range: 22
        access: Allow
        priority: 1001
        direction: Inbound
      - name: SQL
        protocol: Tcp
        destination_port_range: 1433
        access: Allow
        priority: 1002
        direction: Inbound
    state: "{{ status }}"
  tags:
    - sqlnsg
    - sql

- name: Aanmaken Sqlserver NIC
  azure_rm_networkinterface:
    resource_group: "{{ resourcegroup }}"
    name: "{{ env_short }}-{{ sqlname }}"
    virtual_network: "{{ env_short }}-{{ vnetname }}"
    subnet: "{{ env_short }}-Back-End"
    security_group: "{{ env_short }}-{{ sqlname }}"
    private_ip_address: "{{ private_ip_sql }}"
    private_ip_allocation_method: Static
    state: "{{ status }}"
  tags:
    - sqlnic
    - sql

- name: Aanmaken SQL-VM
  azure_rm_virtualmachine:
    resource_group: "{{ resourcegroup }}"
    name: "{{ env_short }}-{{ sqlname }}"
    vm_size: Standard_B2s
    admin_username: "{{ adminname }}"
    ssh_password_enabled: false
    ssh_public_keys:
      - path: /home/{{ adminname }}/.ssh/authorized_keys
        key_data: "{{ sshkey }}"
    network_interfaces: "{{ env_short }}-{{ sqlname }}"
    managed_disk_type: Standard_LRS
    image:
      offer: UbuntuServer
      publisher: Canonical
      sku: 18.04-LTS
      version: latest
    state: "{{ status }}"

  tags:
  - sqlvm
  - sql
