- name: Aanmaken Availability-set
  azure_rm_availabilityset:
    name: "{{ availabilityset_name }}"
    resource_group: "{{ resourcegroep }}"
    state: "{{ status }}"

- name: NSG maken voor virtual machines
  azure_rm_securitygroup:
    resource_group: A2S2_GROEP_03
    name: "{{ item.vmname }}"
    state: "{{ status }}"
    rules:
      - name: SSH
        protocol: Tcp
        destination_port_range: 22
        access: Allow
        priority: 1001
        direction: Inbound
      - name: HTTP
        protocol: Tcp
        destination_port_range: 80
        access: Allow
        priority: 1002
        direction: Inbound
  with_items: "{{ virtualmachine.vms }}"

- name: Create Virtual Network Interface Card
  azure_rm_networkinterface:
    resource_group: "{{ resourcegroep }}"
    name: "{{ item.vmname }}"
    virtual_network: MyVnet
    subnet: Front-End
    state: present
    ip_configurations:
          - name: ipconfig1
            primary: True
            private_ip_address: "{{ item.ip }}"
            load_balancer_backend_address_pools:
              - name: backendaddrpool0
                load_balancer: "{{ loadbalancername }}"
  with_items: "{{ virtualmachine.vms }}"

- name: Aanmaken Webserver virtual machines
  azure_rm_virtualmachine:
    resource_group: "{{ resourcegroep }}"
    name: "{{ item.vmname }}"
    state: "{{ status }}"
    availability_set: "{{ availabilityset_name }}"
    vm_size: "{{ item.vmsize }}"
    admin_username: "{{ adminname }}"
    ssh_password_enabled: false
    ssh_public_keys:
      - path: /home/{{ adminname }}/.ssh/authorized_keys
        key_data: "{{ sshkey }}"
    network_interfaces: "{{ item.vmname }}"
    image:
      offer: UbuntuServer
      publisher: Canonical
      sku: 16.04-LTS
      version: latest
  with_items: "{{ virtualmachine.vms }}"
