---
- hosts: localhost
  connection: local
  tasks:
    - name: Aanmaken VM
      azure_rm_virtualmachine:
        resource_group: A2S2_GROEP_03
        name: vm01
        state: absent
    - name: verwijderen storage acc
      azure_rm_storageaccount:
        resource_group: A2S2_GROEP_03
        name: vm013562
        state: absent
    - name: verwijderen public ip
      azure_rm_networkinterface:
        resource_group: A2S2_GROEP_03
        name: vm1nic
        state: absent
    - name: verwijderen nic
      azure_rm_publicipaddress:
        resource_group: A2S2_GROEP_03
        name: vm01ip
        state: absent
