---
- hosts: 192.168.1.5
  tasks:
  - name: Check if NFS is running.
    service:
      name: "nfs-kernel-server"
      state: started
      enabled: yes

  - name: Check NFS Status
    command: systemctl -q is-active nfs-kernel-servers
    check_mode: no
    failed_when: false
    changed_when: false
    register: nfs_service_status

  - local_action: copy content="NFS-kernel-server is {{ (nfs_service_status.rc == 0) | ternary('up', 'down') }}" dest=/home/ansibleuser/output
