---
- hosts: 192.168.1.5
  tasks:
  - name: Check NFS server status
    service:
      name: "nfs-kernel-server"
      state: started
      enabled: yes
      register: service_nfs_status

  - local_action: copy content={{ service_nfs_status }} dest=/home/ansibleuser/output
