---
- hosts: 192.168.1.5
  tasks:
  - name: Check if NFS is running.
    service:
      name: "nfs-kernel-server"
      state: started
      enabled: yes
    become: yes

  - name: Check NFS Status
    shell: systemctl show -p ActiveState nfs-kernel-server | sed 's/ActiveState=//g'
    #check_mode: no
    #failed_when: false
    #changed_when: false
    register: nfs_service_status
    become: yes

  - name: Write results
    local_action: copy content="NFS-kernal-server is up!" dest=/home/ansibleuser/output
    when: {{ nfs_service_status.failed }} == 'failed'

  - name: Write results
    local_action: copy content="NFS-kernal-server is down!" dest=/home/ansibleuser/output
    when: {{ nfs_service_status.failed }} != 'failed'
