---
- hosts: 192.168.1.5
  tasks:
  - name: Check NFS server status
    service:
      name: "{{ item }}"
      state: started
      enabled: yes
    with_items:
      - nfs-kernel-server

  - local_action: copy content={{ service_nfs_status }} dest=/home/ansibleuser/output
