---
- hosts: 192.168.1.5
  tasks:
  - name: Check if NFS is running.
    service:
      name: "nfs-kernel-server"
      state: started
      enabled: yes
      register: nfs_status
    become: yes

  - debug: msg="NFS-kernel-server is running."
      when: nfs_status.stdout.find("running") != -1
  - debug: msg="NFS-kernl-server is not running."
      when: nfs_status.stdout.find("running") == -1

  - local_action: copy content={{  dest=/home/ansibleuser/output
