- name: Remove Webserver virtual machines
  azure_rm_virtualmachine:
    resource_group: "{{ resourcegroep }}"
    name: "{{ env_short}}-{{ item.vmname }}"
    state: absent
    availability_set: "{{ env_short}}-{{ availabilityset_name }}"
    vm_size: "{{ item.vmsize }}"
    admin_username: "{{ adminname }}"
    ssh_password_enabled: false
    ssh_public_keys:
      - path: /home/{{ adminname }}/.ssh/authorized_keys
        key_data: "{{ sshkey }}"
    network_interfaces: "{{ env_short}}-{{ item.vmname }}"
    image:
      offer: UbuntuServer
      publisher: Canonical
      sku: 16.04-LTS
      version: latest
  with_items: "{{ virtualmachine.vms }}"

- name: Remove Virtual Network Interface Card
  azure_rm_networkinterface:
    resource_group: "{{ resourcegroep }}"
    name: "{{ env_short}}-{{ item.vmname }}"
    virtual_network: "{{ env_short}}-{{ vnetname }}"
    subnet: "{{ env_short}}-Front-End"
    state: absent
    ip_configurations:
          - name: ipconfig1
            primary: True
            private_ip_address: "{{ item.ipaddress }}"
            load_balancer_backend_address_pools:
              - name: backendaddrpool0
                load_balancer: "{{ env_short}}-{{ loadbalancername }}"
  with_items: "{{ virtualmachine.vms }}"

- name: Remove Webserver NSG
  azure_rm_securitygroup:
    resource_group: A2S2_GROEP_03
    name: "{{ env_short}}-{{ item.vmname }}"
    state: absent
    rules:
      - name: SSH
        protocol: Tcp
        destination_port_range: 22
        access: Allow
        priority: 1001
        direction: Inbound
      - name: HTTP
        protocol: Tcp
        destination_port_range: 80
        access: Allow
        priority: 1002
        direction: Inbound
  with_items: "{{ virtualmachine.vms }}"


- name: Remove Availability-set
  azure_rm_availabilityset:
    name: "{{ env_short}}-{{ availabilityset_name }}"
    resource_group: "{{ resourcegroep }}"
    state: absent

- name: Remove Backup-VM
  azure_rm_virtualmachine:
    resource_group: A2S2_GROEP_03
    name: "{{ env_short}}-{{ backupname }}"
    vm_size: Standard_B2s
    admin_username: "{{ adminname }}"
    ssh_password_enabled: false
    ssh_public_keys:
      - path: /home/{{ adminname }}/.ssh/authorized_keys
        key_data: "{{ sshkey }}"
    network_interfaces: "{{ env_short}}-{{ backupname }}"
    managed_disk_type: Standard_LRS
    image:
      offer: UbuntuServer
      publisher: Canonical
      sku: 16.04-LTS
      version: latest
    state: absent

  tags:
  - backupvm
  - backup

- name: Remove virtual nic for Backupserver
  azure_rm_networkinterface:
    resource_group: "{{ resourcegroup }}"
    name: "{{ env_short}}-{{ backupname }}"
    virtual_network: "{{ env_short}}-{{ vnetname }}"
    subnet: "{{ env_short}}-Back-End"
    security_group: "{{ env_short}}-{{ backupname }}"
    private_ip_address: "{{ private_ip_backup }}"
    private_ip_allocation_method: Static
    state: absent
  tags:
    - backupnic
    - backup


- name: Remove Network Security Group Backupserver
  azure_rm_securitygroup:
    resource_group: "{{ resourcegroup }}"
    name: "{{ env_short}}-{{ backupname }}"
    rules:
      - name: SSH
        protocol: Tcp
        destination_port_range: 22
        access: Allow
        priority: 1001
        direction: Inbound
    state: absent
  tags:
    - backupnsg
    - backup

- name: Remove SQL-VM
  azure_rm_virtualmachine:
    resource_group: A2S2_GROEP_03
    name: "{{ env_short}}-{{ sqlname }}"
    vm_size: Standard_B2s
    admin_username: "{{ adminname }}"
    ssh_password_enabled: false
    ssh_public_keys:
      - path: /home/{{ adminname }}/.ssh/authorized_keys
        key_data: "{{ sshkey }}"
    network_interfaces: "{{ env_short}}-{{ sqlname }}"
    managed_disk_type: Standard_LRS
    image:
      offer: UbuntuServer
      publisher: Canonical
      sku: 16.04-LTS
      version: latest
    state: absent

  tags:
  - sqlvm
  - sql

- name: Remove virtual nic for Sqlserver
  azure_rm_networkinterface:
    resource_group: "{{ resourcegroup }}"
    name: "{{ env_short}}-{{ sqlname }}"
    virtual_network: "{{ env_short}}-{{ vnetname }}"
    subnet: "{{ env_short}}-Back-End"
    security_group: "{{ env_short}}-{{ sqlname }}"
    private_ip_address: "{{ private_ip_sql }}"
    private_ip_allocation_method: Static
    state: absent
  tags:
    - sqlnic
    - sql


- name: Remove Network Security Group Sqlserver
  azure_rm_securitygroup:
    resource_group: "{{ resourcegroup }}"
    name: "{{ env_short}}-{{ sqlname }}"
    rules:
      - name: SSH
        protocol: Tcp
        destination_port_range: 22
        access: Allow
        priority: 1001
        direction: Inbound
    state: absent
  tags:
    - sqlnsg
    - sql

- name: Remove NFSServer
  azure_rm_virtualmachine:
    resource_group: A2S2_GROEP_03
    name: "{{ env_short}}-{{ nfsname }}"
    vm_size: Standard_B2s
    admin_username: "{{ adminname }}"
    ssh_password_enabled: false
    ssh_public_keys:
      - path: /home/{{ adminname }}/.ssh/authorized_keys
        key_data: "{{ sshkey }}"
    network_interfaces: "{{ env_short}}-{{ nfsname }}"
    managed_disk_type: Standard_LRS
    image:
      offer: UbuntuServer
      publisher: Canonical
      sku: 16.04-LTS
      version: latest
    state: absent

  tags:
  - nfsvm
  - nfs

- name: Remove virtual nic for nfsserver
  azure_rm_networkinterface:
    resource_group: "{{ resourcegroup }}"
    name: "{{ env_short}}-{{ nfsname }}"
    virtual_network: "{{ env_short}}-{{ vnetname }}"
    subnet: "{{ env_short}}-Back-End"
    security_group: "{{ env_short}}-{{ nfsname }}"
    private_ip_address: "{{ private_ip_nfs }}"
    private_ip_allocation_method: Static
    state: absent
  tags:
    - nfsnic
    - nfs

- name: Remove Network Security Group for nfsserver
  azure_rm_securitygroup:
    resource_group: "{{ resourcegroup }}"
    name: "{{ env_short}}-{{ nfsname }}"
    rules:
      - name: SSH
        protocol: Tcp
        destination_port_range: 22
        access: Allow
        priority: 1001
        direction: Inbound
    state: absent
  tags:
    - nfsnsg
    - nfs


- name: remove VM managementnode
  azure_rm_virtualmachine:
    resource_group: A2S2_GROEP_03
    name: "{{ env_short}}-{{ managementnaam }}"
    vm_size: Standard_B2s
    admin_username: "{{ adminname }}"
    ssh_password_enabled: false
    ssh_public_keys:
      - path: /home/{{ adminname }}/.ssh/authorized_keys
        key_data: "{{ sshkey }}"
    network_interfaces: "{{ env_short}}-{{ managementnaam }}"
    managed_disk_type: Standard_LRS
    image:
      offer: UbuntuServer
      publisher: Canonical
      sku: 16.04-LTS
      version: latest
    state: absent
  tags:
  - managementvm
  - management

- name: remove virtual network interface card
  azure_rm_networkinterface:
    resource_group: "{{ resourcegroup }}"
    name: "{{ env_short}}-{{ managementnaam }}"
    virtual_network: "{{ env_short}}-{{ vnetname }}"
    subnet: "{{ env_short}}-Management"
    security_group: "{{ env_short}}-Management-NSG"
    public_ip_name: "{{ env_short}}-{{ managementnaam }}"
    private_ip_allocation_method: Static
    private_ip_address: "{{ private_ip_management }}"
    state: absent
  tags:
    - managementnic
    - management

- name: remove Network Security Group that allows SSH
  azure_rm_securitygroup:
    resource_group: "{{ resourcegroup }}"
    name: "{{ env_short}}-{{ managementnaam }}"
    rules:
      - name: SSH
        protocol: Tcp
        destination_port_range: 22
        access: Allow
        priority: 1001
        direction: Inbound
    state: absent
  tags:
    - managementnsg
    - management
- name: remove public IP address
  azure_rm_publicipaddress:
    resource_group: "{{ resourcegroup }}"
    allocation_method: Static
    name: "{{ env_short}}-{{ managementnaam }}"
    state: absent
  tags:
  - management
  - managementip

- name: remove Loadbalancer
  azure_rm_loadbalancer:
    resource_group: "{{ resourcegroup }}"
    name: "{{ env_short}}-{{ loadbalancername }}"
    sku: Basic
    state: absent
    public_ip: "{{ env_short}}-{{ loadbalancername }}"
    probe_protocol: Tcp
    probe_port: 80
    probe_interval: 10
    probe_fail_count: 3
    protocol: Tcp
    load_distribution: Default
    frontend_port: 80
    backend_port: 80
    idle_timeout: 4
    natpool_frontend_port_start: 50000
    natpool_frontend_port_end: 50040
    natpool_backend_port: 22
    natpool_protocol: Tcp
  tags:
  - loadbalancer

- name: remove loadbalancer IP
  azure_rm_publicipaddress:
    resource_group: "{{ resourcegroup }}"
    name: "{{ env_short}}-{{ loadbalancername }}"
    allocation_method: static
    state: absent
  tags:
  - loadbalancerip
  - loadbalancer

- name: Remove Subnets
  azure_rm_subnet:
    resource_group: "{{ resourcegroup }}"
    name: "{{ env_short}}-{{ item.subnetname }}"
    address_prefix: "{{ item.prefix }}"
    virtual_network: "{{ env_short}}-{{ vnetname }}"
    state: absent
    security_group: "{{ env_short}}-{{ item.securitygroup }}"
  with_items: "{{ network.subnets }}"
  tags:
  - subnet
  - network

- name: Remove NSG
  azure_rm_securitygroup:
    resource_group: "{{ resourcegroup }}"
    name: "{{ env_short}}-{{ item.nsgname }}"
    rules:
      - name: "{{ item.rulename }}"
        protocol: "{{ item.protocol }}"
        destination_port_range: "{{ item.destportrange }}"
        access: "{{ item.access }}"
        priority: "{{ item.priority }}"
        direction: "{{ item.direction}}"
    state: absent
  with_items: "{{ network.nsgs}}"
  tags:
  - subnetnsg
  - network



- name: remove Vnet
  azure_rm_virtualnetwork:
    resource_group: "{{ resourcegroup }}"
    name: "{{ env_short}}-{{ vnetname }}"
    address_prefixes_cidr:
      - "{{ vnetprefix }}"
    state: absent
  tags:
  - vnet
  - network
