- name: Include network vars
  include_vars:
    dir: vars
  tags:
  - vnet
  - subnet
  - subnetnsg

- name: Aanmaken Vnet
  azure_rm_virtualnetwork:
    resource_group: "{{ resourcegroup }}"
    name: "{{ vnetname }}"
    address_prefixes_cidr:
      - "{{ vnetprefix }}"
    state: "{{ status }}"
  tags:
  - vnet

- name: Toevoegen NSG
  azure_rm_securitygroup:
    resource_group: "{{ resourcegroup }}"
    name: "{{ item.nsgname }}"
    rules:
      - name: "{{ item.rulename }}"
        protocol: "{{ item.protocol }}"
        destination_port_range: "{{ item.destportrange }}"
        access: "{{ item.access }}"
        priority: "{{ item.priority }}"
        direction: "{{ item.direction}}"
    state: "{{ item.status }}"
  with_items: "{{ network.nsgs}}"
  tags:
  - subnetnsg

- name: Toevoegen Subnets
  azure_rm_subnet:
    resource_group: "{{ resourcegroup }}"
    name: "{{ item.subnetname }}"
    address_prefix: "{{ item.prefix }}"
    virtual_network: "{{ vnetname }}"
    state: "{{ item.status }}"
    security_group: "{{ item.securitygroup }}"
  with_items: "{{ network.subnets }}"
  tags:
  - subnet
