- name: Include webserver Vars
  include_vars:
    dir: vars
  tags:
  - scaleset
  - nsgscaleset


- name: Create Network Security Group that allows SSH
  azure_rm_securitygroup:
    resource_group: "{{ resourcegroup }}"
    name: "{{ vmscalesetname }}"
    state: "{{ status }}"
    rules:
      - name: SSH
        protocol: Tcp
        destination_port_range: 22
        access: Allow
        priority: 1001
        direction: Inbound
  tags:
  - nsgscaleset

- name: Create Scale Set
  azure_rm_virtualmachinescaleset:
    resource_group: "{{ resourcegroup }}"
    name: "{{ vmscalesetname }}"
    state: "{{ status }}"
    vm_size: Standard_B2s
    admin_username: "{{ adminname }}"
    ssh_public_keys:
    - path: /home/"{{adminname}}"/.ssh/authorized_keys
      key_data: "{{ sshkey }}"
    ssh_password_enabled: false
    capacity: 2
    virtual_network_name: "{{ vnetname }}"
    subnet_name: "{{ frontendsubnetname }}"
    upgrade_policy: Manual
    tier: Standard
    managed_disk_type: Standard_LRS
    os_disk_caching: ReadWrite
    image:
      offer: UbuntuServer
      publisher: Canonical
      sku: 16.04-LTS
      version: latest
    load_balancer: "{{ loadbalancername }}"
    data_disks:
      - lun: 0
        disk_size_gb: 20
        managed_disk_type: Standard_LRS
        caching: ReadOnly
  tags:
  -  scaleset
