---
- hosts: localhost
  connection: local
  tasks:
    - name: Create Virtual Network Interface Card
      azure_rm_networkinterface:
        resource_group: A2S2_GROEP_03
        name: vm02nic
        virtual_network: MyVnet
        subnet: Front-End
#        security_group: front-end
#        public_ip_name: vm01ip
        state: absent
