---
- hosts: localhost
  connection: local
  tasks:
    - name: Aanmaken VM
      azure_rm_virtualmachine:
        resource_group: A2S2_GROEP_03
        name: vm01
        availability_set: gratisbiervoorhugo
        vm_size: Standard_B2s
        admin_username: rens
        admin_password: Welkom123!
        network_interfaces: vm01nic
        managed_disk_type: Standard_LRS
        image:
          offer: UbuntuServer
          publisher: Canonical
          sku: 16.04-LTS
          version: latest
